@echo off
echo Cleaning build directory...
rmdir /s /q build 2>nul
mkdir build
echo Configuring with CMake...
cmake -S . -B build -G "NMake Makefiles"
echo Building...
cmake --build build
echo Copying runtime DLLs...
copy external\glfw\lib-vc2022\glfw3.dll build\glfw3.dll >nul
echo Done.